### ISSUE TITLE
How to get CERTKEY 

### ISSUE THREAD

**Issue by hijizaly** [husseinmkwizu/node-tra#1]
Hi..
Sorry, Bro! im stack on how to get CERTKEY _(EFDSERIAL)_.

**Comment by husseinmkwizu** [comment]
Hi @hijizaly , EFDSERIAL is used when uploading receipt. You need to call registration API to get it.

Parameters for registration API are all provided to you by TRA.

```
const response = await sendRegistrationRequest({
  tin: "YOUR TIN",
  certKey: "YOUR CERT KEY",
  signKey: key, //key loaded from first step
  certSerial: "YOUR CERT SERIAL",
  hostname: hostname,
  path: path,
});
```
